import {
  Avater,
  Avater10,
  Avater11,
  Avater12,
  Avater13,
  Avater14,
  Avater15,
  Avater16,
  Avater17,
  Avater18,
  Avater2,
  Avater3,
  Avater4,
  Avater5,
  Avater6,
  Avater7,
  Avater8,
  Avater9,
  Art,
  Code,
  Communication,
  Critical,
  Decision,
  Emotional,
  Entrepreneurship,
  Finance,
  Logical,
  Math,
  Presentation,
  ProblemSolve,
  Responsibility,
  Teamwork,
} from "@/assets";

export const avatars = [
  { id: 1, icon: Avater },
  { id: 2, icon: Avater2 },
  { id: 3, icon: Avater3 },
  { id: 4, icon: Avater4 },
  { id: 5, icon: Avater5 },
  { id: 6, icon: Avater6 },
  { id: 7, icon: Avater7 },
  { id: 8, icon: Avater8 },
  { id: 9, icon: Avater9 },
  { id: 10, icon: Avater10 },
  { id: 11, icon: Avater11 },
  { id: 12, icon: Avater12 },
  { id: 13, icon: Avater13 },
  { id: 14, icon: Avater14 },
  { id: 15, icon: Avater15 },
  { id: 16, icon: Avater16 },
  { id: 17, icon: Avater17 },
  { id: 18, icon: Avater18 },
];

export const skills = [
  {
    id: 1,
    title: "Logical Thinking",
    icon: Logical,
  },
  {
    id: 2,
    title: "Problem Solving",
    icon: ProblemSolve,
  },
  {
    id: 3,
    title: "Artistic Expression",
    icon: Art,
  },
  {
    id: 4,
    title: "Basic Math Concepts",
    icon: Math,
  },
  {
    id: 5,
    title: "Coding for Kids",
    icon: Code,
  },
  {
    id: 6,
    title: "Presentation Skills",
    icon: Presentation,
  },
  {
    id: 7,
    title: "Communication Skills",
    icon: Communication,
  },
  {
    id: 8,
    title: "Basic Financial Literacy",
    icon: Finance,
  },
  {
    id: 9,
    title: "Teamwork",
    icon: Teamwork,
  },
  { id: 10, title: "Entrepreneurship", icon: Entrepreneurship },
  {
    id: 11,
    title: "Emotional Intelligence",
    icon: Emotional,
  },
  {
    id: 12,
    title: "Decision-Making",
    icon: Decision,
  },
  {
    id: 13,
    title: "Critical Thinking",
    icon: Critical,
  },
  {
    id: 14,
    title: "Responsibility & Independence",
    icon: Responsibility,
  },
];
